common:
    app: tavla
    shortname: tavla
    team: selvbetjent
    ingress:
        enabled: true
        trafficType: public
    service:
        internalPort: 3000
    container:
        image: <+artifacts.primary.image>
        cpu: 0.3
        memory: 512
        probes:
            enabled: true
            spec:
                startupProbe:
                    tcpSocket:
                        port: 3000
                    periodSeconds: 1
                    timeoutSeconds: 1
                    failureThreshold: 300
                livenessProbe:
                    tcpSocket:
                        port: 3000
                    periodSeconds: 5
                    successThreshold: 1
                    failureThreashold: 6
                    timeoutSeconds: 1
                readinessProbe:
                    tcpSocket:
                        port: 3000
                    periodSeconds: 5
                    successThreshold: 1
                    failureThreashold: 6
                    timeoutSeconds: 1
    configmap:
        enabled: true
        data:
            NODE_ENV: production
            NEXT_PUBLIC_ENV: dev
