version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/tavla"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "fix(dependencies):"
      groups:
          patch-minor-dependencies:
              update-types:
                  - "patch"
                  - "minor"
          major-dependencies:
              update-types:
                  - "major"
