import 'styles/imports.css'
import 'styles/fonts.css'
import 'styles/reset.css'
import 'app/(root)/globals.css'
import Head from 'next/head'
import Script from 'next/script'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <Script
                    strategy="beforeInteractive"
                    src="/global-this.js"
                ></Script>
            </head>

            <body>{children}</body>
        </html>
    )
}
