common:
    app: tavla
    shortname: tavla
    team: selvbetjent
    ingress:
        enabled: true
        trafficType: public
    service:
        internalPort: 3000
    deployment:
        prometheus:
            path: /actuator/prometheus
    container:
        image: <+artifacts.primary.image>
        cpu: 0.3
        memory: 512
        env:
            - name: BACKEND_API_KEY
              valueFrom:
                  secretKeyRef:
                      name: backend
                      key: api-key

            - name: SLACK_WEBHOOK_URL
              valueFrom:
                  secretKeyRef:
                      name: slack-webhook
                      key: url

        probes:
            enabled: true
            spec:
                startupProbe:
                    tcpSocket:
                        port: 3000
                    periodSeconds: 1
                    timeoutSeconds: 1
                    failureThreshold: 300
                livenessProbe:
                    httpGet:
                        path: /actuator/health/liveness
                        port: 3000
                    periodSeconds: 5
                    successThreshold: 1
                    timeoutSeconds: 1
                readinessProbe:
                    tcpSocket:
                        port: 3000
                    periodSeconds: 5
                    successThreshold: 1
                    timeoutSeconds: 1

    configmap:
        enabled: true
        data:
            NODE_ENV: production
