compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs

npmMinimalAgeGate: 5760

enableHardenedMode: true

enableScripts: false
