query driveDistance($from: InputCoordinates!, $to: InputCoordinates!) {
    trip(
        from: { coordinates: $from }
        to: { coordinates: $to }
        modes: { directMode: car, transportModes: [] }
    ) {
        tripPatterns {
            duration
            streetDistance
            legs {
                expectedStartTime
                expectedEndTime
                mode
                distance
                line {
                    id
                    publicCode
                }
            }
        }
    }
}
