query QuayEstimatedCalls(
    $quayId: String!
    $arrivalDeparture: ArrivalDeparture = departures
) {
    quay(id: $quayId) {
        estimatedCalls(
            numberOfDepartures: 1000
            numberOfDeparturesPerLineAndDestinationDisplay: 1
            timeRange: 2592000
            includeCancelledTrips: true
            arrivalDeparture: $arrivalDeparture
        ) {
            destinationDisplay {
                frontText
            }
            serviceJourney {
                line {
                    id
                }
            }
        }
    }
}
