export { default as BackButton } from './backButton/BackButton'
export { default as Checkbox } from './checkbox/Checkbox'
export { default as Slider } from './Slider'
export { default as Footer } from './footer/Footer'
export { default as Clock } from './Clock'
