export { default as useBikeRentalStations } from './useBikeRentalStations'
export { default as useNearestPlaces } from './useNearestPlaces'
export { default as useStopPlacesWithDepartures } from './useStopPlacesWithDepartures'
export { default as useScooters } from './useScooters'
export { default as useWalkTime } from './useWalkTime'
export { default as useWeather } from './useWeather'
export { countScootersByOperator } from './useScooters'
