common:
  app: backend
  shortname: backend
  team: selvbetjent
  ingress:
    enabled: true
    trafficType: public
  service:
    internalPort: 3000
  secrets:
    backend:
      - BACKEND_API_KEY
    redis:
      - REDIS_PASSWORD
  container:
    image: <+artifacts.primary.image>
    cpu: 0.3
    memory: 512
    probes:
      enabled: true
      spec:
        startupProbe:
          tcpSocket:
            port: 3000
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 300
        livenessProbe:
          httpGet:
            path: /alive
            port: 3000
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 3000
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
    prometheus:
      enabled: true
      path: /metrics
      port: 3000
