common:
  app: backend
  shortname: backend
  team: selvbetjent
  ingress:
    enabled: true
    trafficType: public
  service:
    internalPort: 3000
  secrets:
    backend:
      - BACKEND_API_KEY
  container:
    image: <+artifacts.primary.image>
    cpu: 0.3
    memory: 512
    env:
      - name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis
            key: redis-password
    probes:
      enabled: true
      spec:
        startupProbe:
          tcpSocket:
            port: 3000
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 300
        livenessProbe:
          httpGet:
            path: /alive
            port: 3000
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 3000
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
