export type transportMode =
    | 'metro'
    | 'bus'
    | 'plane'
    | 'helicopter'
    | 'tram'
    | 'funicular'
    | 'cableway'
    | 'taxi'
    | 'bicycle'
    | 'walk'
    | 'rail'
    | 'ferry'
    | 'carferry'
    | 'mobility'
