#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! git diff --cached --exit-code -s next-tavla
then
	echo "Files changed in next-tavla"
	cd next-tavla
	yarn lint
	yarn typecheck
	yarn prettier
	cd ..
fi

