name: cd/backend-dev

on:
  workflow_dispatch:

jobs:
  docker-build:
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      context: backend
      dockerfile: backend/Dockerfile
      image_name: tavla-backend

  docker-push:
    needs: [docker-build]
    uses: entur/gha-docker/.github/workflows/push.yml@v1
    with:
      image_name: tavla-backend

  helm-deploy-dev:
    needs: [docker-push]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: dev
      chart: backend/helm/backend
      image: ${{ needs.docker-push.outputs.image_name }}:${{ needs.docker-push.outputs.image_tag}}
      release_name: backend
