name: cd/frontend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "next-tavla/**"

jobs:
  docker-push:
    uses: entur/gha-docker/.github/workflows/push.yml@v1.2.3
    with:
      environment: frontend-prd
      context: next-tavla

  helm-deploy-dev:
    needs: [docker-push]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1.0.4
    with:
      environment: frontend-dev
      chart: next-tavla/helm/tavla
      image: ${{ needs.docker-push.outputs.image_name }}:${{ needs.docker-push.outputs.image_tag}}

  helm-deploy-prd:
    needs: [docker-push, helm-deploy-dev]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1.0.4
    with:
      environment: frontend-prd
      chart: next-tavla/helm/tavla
      image: ${{ needs.docker-push.outputs.image_name }}:${{ needs.docker-push.outputs.image_tag}}
