name: cd/frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "tavla/**"

jobs:
  docker-push:
    uses: entur/gha-docker/.github/workflows/push.yml@v1.2.3
    with:
      environment: prd
      context: tavla
      image_name: tavla/frontend

  helm-deploy-dev:
    needs: [docker-push]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1.0.4
    with:
      environment: dev
      chart: tavla/helm/tavla
      image: ${{ needs.docker-push.outputs.image_name }}:${{ needs.docker-push.outputs.image_tag}}

  approval-step:
    runs-on: ubuntu-24.04
    needs: [helm-deploy-dev]
    environment: apr
    steps:
      - name: Approval step
        id: approval
        shell: bash
        run: echo "Approve the deployment to prod"

  helm-deploy-prd:
    needs: [docker-push, approval-step]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1.0.4
    with:
      environment: prd
      chart: tavla/helm/tavla
      image: ${{ needs.docker-push.outputs.image_name }}:${{ needs.docker-push.outputs.image_tag}}
