name: CI

on:
  pull_request:

jobs:
  lint-dockerfile:
    uses: entur/gha-docker/.github/workflows/lint.yml@v1.0.0
    with:
      dockerfile: next-tavla/Dockerfile
      ignore: DL3018,DL3019,DL3059
