name: Deploy Beta prod

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.BETA_PROD_ID }}
  RUN_REGION: ${{ secrets.BETA_RUN_REGION }}
  POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}
  POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next-tavla
    steps:
      - uses: actions/checkout@v3
      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.DEPLOY_BETA_PROD }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"
          project_id: "${{ secrets.BETA_PROD_ID }}"

      - name: "Build container image"
        run: "gcloud builds submit . --substitutions _ENV=prod,_POSTHOG_KEY=$POSTHOG_KEY,_POSTHOG_HOST=$POSTHOG_HOST,COMMIT_SHA=$GITHUB_SHA"
      - name: "Deploy"
        run: >
          gcloud run deploy $PROJECT_ID --image eu.gcr.io/$PROJECT_ID/$PROJECT_ID:$GITHUB_SHA
          --region $RUN_REGION --service-account="application@ent-tavla-prd.iam.gserviceaccount.com" --allow-unauthenticated
