name: Linting and Formatting
on:
  push:
    branches-ignore:
      - master
    paths:
      - "tavla/**"
jobs:
  linting_and_formatting:
    name: Verifies linting and formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tavla
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install
      - name: Lint
        run: yarn run lint
